workspace 'Bookworm.xcworkspace'

target 'BookwormPhone' do
	project 'BookwormPhone/BookwormPhone.xcodeproj'
	platform :ios, '7.0'
	pod 'Masonry', '~> 1.0.2'
    pod 'AMap3DMap'
    pod 'AMapSearch'
end

target 'BookwormPad' do
	platform :ios, '7.0'
	project 'BookwormPad/BookwormPad.xcodeproj'
	pod 'Masonry', '~> 1.0.2'
end

target 'BookwormFramework' do 
	project 'BookwormFramework/BookwormFramework.xcodeproj'
	pod 'AFNetworking', '~> 3.1.0'
 	pod 'FMDB', '~> 2.6.2'
	pod 'SDWebImage', '~> 3.8.2'
    pod 'JSPatch', '~>1.1.2'
end
